DROP TABLE IF EXISTS dw.dim_customer;
CREATE TABLE dw.dim_customer (
    customer_key        INT           NOT NULL AUTO_INCREMENT PRIMARY KEY,
    customer_number     INT           NOT NULL,
    customer_name                VARCHAR(255)  NOT NULL,
    gender              VARCHAR(100)  NOT NULL,
    date_of_birth       DATE          NOT NULL,
    date_registered     DATE          NOT NULL,
    age_group           VARCHAR(20)   NOT NULL,
    city                VARCHAR(100)  NOT NULL,
    state               CHAR(10)      NULL,
    zipcode             VARCHAR(20)   NOT NULL,
    country             VARCHAR(100)  NOT NULL,
    customer_type       CHAR(1)       NOT NULL,
    status              CHAR(2)       NOT NULL,
    occupation          VARCHAR(100)  NULL,
    occupation_category VARCHAR(100)  NOT NULL,
    household_income    VARCHAR(50)   NULL,
    permission          CHAR(1)       NULL,
    preferred_channel1  VARCHAR(100)  NULL,
    preferred_channel2  VARCHAR(50)   NULL,
    interest1           VARCHAR(100)  NULL,
    interest2           VARCHAR(100)  NULL,
    interest3           VARCHAR(100)  NULL,
    customer_effective_start_date      DATE          NOT NULL,
    customer_effective_end_date         DATE          NULL,
    customer_current_flag          TINYINT    NOT NULL DEFAULT 1,
    CONSTRAINT uq_dim_customer_version
        UNIQUE (customer_number, customer_effective_start_date)
);